### ISSUE TITLE
2020年2月の旅行先

### ISSUE THREAD

**Issue by moteki13** [moteki13/Shinagawa-demo#1]
・天皇誕生日の連休絡めた3日間
・できれば海外
・スターアライアンスを利用する
・費用は100,000円以内

**Comment by macnica-dev12** [comment]
@moteki13 
賛成！
いろいろ調べてみます。

**Comment by moteki13** [comment]
@macnica-dev12 
ありがとう 😄 楽しみにしてます！

**Comment by macnica-dev12** [comment]
@moteki13 
費用100,000円以内ってのは、ホテル代やアクティビティも込みで ❓ ❓

**Comment by moteki13** [comment]
@macnica-dev12 
早速ありがとうございます 👍 
費用の100,000円は、飛行機代とホテル代を想定してます！

**Comment by moteki13** [comment]
@macnica-dev12
**決まった？？** 
*kimatta??*
決まったかー？？

**Comment by moteki13** [comment]
- [ ] いちばんめ
1. にばんめ
- さんばんめ
-
