### ISSUE TITLE
行き先候補を検討しましょう

### ISSUE THREAD

**Issue by moteki13** [moteki13/Shinagawa-demo#22]
社員旅行の行先を検討しましょう。
下記では多すぎるので、4つくらいに絞りませんか ❓ ❓ 
シンガポール
マレーシア
タイ
カンボジア
ベトナム
インドネシア
スペイン
ポルトガル

**Comment by macnica-dev12** [comment]
@moteki13 
４つ、いいですね ❗️ 4つくらいが選びやすいですもんね 😄 
下記でいかがでしょうか？？
シンガポール
マレーシア
タイ
カンボジア

**Comment by moteki13** [comment]
@macnica-dev12 
早速ありがとうございます 🙏 
では、いただいた4つにてアンケート作成しますね ❗️

**Comment by moteki13** [comment]
@macnica-dev12 
変更反映しました、ありがとうございました 🙇
