### ISSUE TITLE
行き先を決めましょう

### ISSUE THREAD

**Issue by moteki13** [moteki13/Shinagawa-demo#25]
行き先候補を5つに絞ってアンケートを取りたいと思います。
2泊3日の旅行、どちらにしましょうか ❓ ❓ 😄 🙇 
シンガポール
マレーシア
タイ
カンボジア
ベトナム
インドネシア
スペイン
ポルトガル

**Comment by macnica-dev12** [comment]
@moteki13 
下記5つではどう ❓ 
シンガポール
マレーシア
タイ
ベトナム
インドネシア

**Comment by moteki13** [comment]
@macnica-dev12 
早速ありがとうございます 💯
2泊3日なんで、そうなりますよね！アンケート飛ばすようにします
