### ISSUE TITLE
行き先の候補を絞りましょう

### ISSUE THREAD

**Issue by moteki13** [moteki13/Shinagawa-demo#27]
現在、行き先の案は下記の通りです。行き先を絞りましょう。
5つくらいにしぼりましょう。2泊3日です。
[行き先]
シンガポール
マレーシア
タイ
カンボジア
ベトナム
インドネシア
スペイン
ポルトガル
イタリア

**Comment by macnica-dev12** [comment]
@moteki13 
下記ではいかがでしょうか。
[行き先]
シンガポール
マレーシア
タイ
ベトナム
インドネシア

**Comment by moteki13** [comment]
@macnica-dev12 
早速ありがとうございます 😄 🙇 🙏
