### ISSUE TITLE
行き先を候補を決めましょう

### ISSUE THREAD

**Issue by moteki13** [moteki13/Shinagawa-demo#29]
2泊3日で、かついきやすい場所を5つくらいでアンケート取りたいと思ってます。
候補を5つに絞りたいと思います。

シンガポール
マレーシア
タイ
カンボジア
ベトナム
インドネシア
スペイン
ポルトガル

**Comment by macnica-dev12** [comment]
@moteki13 
シンガポール
マレーシア
タイ
ベトナム
インドネシア

**Comment by macnica-dev12** [comment]
@moteki13 
- 上記でどうですか ❓

**Comment by moteki13** [comment]
@macnica-dev12 
早速ありがとうございます 🙇 
こちらで修正させていただきます ❗️
