### ISSUE TITLE
旅行の行先を決めましょう

### ISSUE THREAD

**Issue by moteki13** [moteki13/Shinagawa-demo#34]
行き先を5つに絞りましょう。
2泊３日で検討しているんですが、妥当なところはどちらでしょうか。
シンガポール
マレーシア
タイ
カンボジア
ベトナム
インドネシア
スペイン
ポルトガル
イタリア

**Comment by macnica-dev12** [comment]
@moteki13 
下記5つではどうでしょうか ❓ 😄 
シンガポール
マレーシア
タイ
ベトナム
インドネシア

**Comment by moteki13** [comment]
@macnica-dev12 
さっそくありがとうございます 👍 
いただいた意見を反映したいと思います ❗️
