### ISSUE TITLE
ビール買いに行きましょう！

### ISSUE THREAD

**Issue by moteki13** [moteki13/Shinagawa-demo#43]
@hidemaesan @ryosunamucho
日本のビールとアメリカのビールどっちがいいですか？

**Comment by ryosunamucho** [comment]
@moteki13 アメリカのビールですかね。バドワイザーしかわかりませんが。

**Comment by moteki13** [comment]
@ryosunamucho 
了解です。そしたら、リスト修正しますね ❗
